name : Run tests
on: push
jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    env:
      IS_GITHUB_ACTION: "True"
      FE_URL: ${{ secrets.FE_URL }}
      BE_URL: ${{ secrets.BE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Test 
        run: |
            python manage.py test
