name : Run tests
on: push
jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update && sudo apt upgrade
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install docker
        run: sudo apt install docker.io -y
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: run rabbitmq
        run: sudo docker run -d -p 5672:5672 rabbitmq
      - name: run celery
        run: celery -A yummy_yagi worker -l info -P eventlet
      - name: Run Test 
        env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
            python manage.py test
